{
 "title": "Arbitrage Bot",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Records (by table)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as 'Triangular Arbitrage-1 Exchange' FROM crypto_arbitrage_bot.triangular_arbitrage_1_exchange;"
    },
    {
     "rawSql": "SELECT COUNT(*) as 'Arbitrage Records' FROM crypto_arbitrage_bot.arbitrage_records;"
    },
    {
     "rawSql": "SELECT COUNT(*) as 'Price Records' FROM crypto_arbitrage_bot.price_records;"
    }
   ]
  },
  {
   "title": "Total Arbitrage Opportunities",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "arbitrage_bot",
     "rawSql": "SELECT COUNT(*) as 'Regular Arbitrage' FROM crypto_arbitrage_bot.arbitrage_records WHERE is_arbitrage_opportunity = 1;"
    },
    {
     "dataset": "arbitrage_bot",
     "rawSql": "SELECT COUNT(*) as 'Triangular Arbitrage (1 Exchange)' FROM crypto_arbitrage_bot.triangular_arbitrage_1_exchange  WHERE is_triangular_arbitrage_opportunity = 1;"
    }
   ]
  },
  {
   "title": "BTCUSD Arbitrage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, price as Coinbase_Price, exchange FROM crypto_arbitrage_bot.price_records WHERE currency = \"BTCUSD\" AND exchange = \"Coinbase\";"
    },
    {
     "rawSql": "SELECT timestamp, price as Gemini_Price, exchange FROM crypto_arbitrage_bot.price_records WHERE currency = \"BTCUSD\" AND exchange = \"Gemini\";"
    },
    {
     "rawSql": "SELECT timestamp, price as Kraken_Price, exchange FROM crypto_arbitrage_bot.price_records WHERE currency = \"BTCUSD\" AND exchange = \"Kraken\";"
    }
   ]
  },
  {
   "title": "ETHUSD Arbitrage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, price as Coinbase_Price, exchange FROM crypto_arbitrage_bot.price_records WHERE currency = \"ETHUSD\" AND exchange = \"Coinbase\";"
    },
    {
     "rawSql": "SELECT timestamp, price as Gemini_Price, exchange FROM crypto_arbitrage_bot.price_records WHERE currency = \"ETHUSD\" AND exchange = \"Gemini\";"
    },
    {
     "rawSql": "SELECT timestamp, price as Kraken_price, exchange FROM crypto_arbitrage_bot.price_records WHERE currency = \"ETHUSD\" AND exchange = \"Kraken\" GROUP BY timestamp, price, exchange;"
    }
   ]
  },
  {
   "title": "LTCUSD Arbitrage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, price as Coinbase_Price, exchange FROM crypto_arbitrage_bot.price_records WHERE currency = \"LTCUSD\" AND exchange = \"Coinbase\";"
    },
    {
     "rawSql": "SELECT timestamp, price as Gemini_Price, exchange FROM crypto_arbitrage_bot.price_records WHERE currency = \"LTCUSD\" AND exchange = \"Gemini\";"
    },
    {
     "rawSql": "SELECT timestamp, price as Kraken_Price, exchange FROM crypto_arbitrage_bot.price_records WHERE currency = \"LTCUSD\" AND exchange = \"Kraken\";"
    }
   ]
  },
  {
   "title": "Potential Profit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT * FROM crypto_arbitrage_bot.arbitrage_records WHERE projected_profit;"
    }
   ]
  },
  {
   "title": "Triangular Arbitrage (1 Exchange)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "select timestamp, exchange, cross_exchange_rate_difference as \"Gemini\"  from crypto_arbitrage_bot.triangular_arbitrage_1_exchange WHERE exchange=\"Gemini\";"
    }
   ]
  }
 ]
}